In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

# 요청에 필요한 데이터 설정
url = 'https://statiz.sporki.com/stats/?m=team&m2=batting&m3=default&so=WAR&ob=DESC&year=2024&sy=2019&ey=2024&te=&po=&lt=10100&reg=&pe=&ds=&de=&we=&hr=&ha=&ct=&st=&vp=&bo=&pt=&pp=&ii=&vc=&um=&oo=&rr=&sc=&bc=&ba=&li=&as=&ae=&pl=&gc=&lr=&pr=50&ph=&hs=&us=&na=&ls=&sf1=&sk1=&sv1=&sf2=&sk2=&sv2='
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36'}

response = requests.post(url, headers=headers)  # 또는 requests.get() 사용

res = requests.get(url, headers=headers)
res.raise_for_status()

html = response.text

# 응답에서 데이터 추출
soup = BeautifulSoup(html, "html.parser")

rows = []
data = []

trs = soup.find_all("tr")

for tr in trs[2:]:
    tds = tr.find_all("td")
    tds = [td.text for td in tds]
    rows.append(tds)

# print(rows[0])

for row in rows:
    temp = []
    for index in range(1, len(row)-1):
        temp.append(row[index])
    data.append(temp)

In [83]:
pd.reset_option('display.max_rows')
pd.reset_option('display.max_columns')
pd.reset_option('display.width')
pd.reset_option('display.max_colwidth')

team_hitter_df = pd.DataFrame(data, columns=['팀', '시즌', 'WAR', '공격WAR', '수비WAR', '게임수', '타석', '유효타석', '타수', '득점', '안타', '2루타', '3루타', '홈런', '루타', '타점', '도루성공', '도루실패', '4구', '사구', '고의사구', '삼진', '병살타', '희생타', '희생플라이', '타율', '출루율', '장타율', 'OPS', 'R/ePA', '득점 창출력'])

team_hitter_df

,팀,시즌,WAR,공격WAR,수비WAR,게임수,타석,유효타석,타수,득점,...,삼진,병살타,희생타,희생플라이,타율,출루율,장타율,OPS,R/ePA,득점 창출력
0,리그,22,246.20,246.20,0.01,17841,55963,55206,49276,6523,...,10469,1076,610,422,0.260,0.333,0.379,0.712,0.118,100.0
1,리그,19,246.18,246.25,-0.07,17618,55627,55099,49225,6548,...,9595,1122,436,505,0.267,0.337,0.385,0.722,0.119,100.0
2,리그,20,245.60,245.60,0.00,18815,56643,56060,49658,7436,...,9855,1174,486,468,0.273,0.349,0.409,0.758,0.133,100.0
3,리그,23,243.67,243.67,0.00,18236,56231,55462,49236,6622,...,9970,1015,673,485,0.263,0.338,0.374,0.712,0.119,100.0
4,리그,21,242.76,242.76,0.00,18536,56076,55470,48402,6896,...,10196,1078,497,493,0.260,0.346,0.383,0.729,0.124,100.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63,한화,24,6.19,6.65,-0.46,568,1863,1848,1617,236,...,363,27,11,13,0.259,0.346,0.390,0.736,0.128,96.4
64,한화,20,5.73,6.12,-0.39,1886,5483,5430,4862,551,...,1163,119,45,25,0.245,0.320,0.338,0.658,0.102,74.5
65,롯데,19,5.29,11.08,-5.79,1823,5488,5446,4919,578,...,1085,108,35,40,0.250,0.316,0.358,0.674,0.106,81.4
66,키움,24,5.20,5.73,-0.53,539,1806,1792,1599,219,...,338,32,12,19,0.268,0.337,0.394,0.731,0.122,91.9
67,롯데,24,3.70,5.46,-1.76,586,1771,1761,1590,202,...,365,32,10,11,0.265,0.330,0.391,0.721,0.115,90.1